<?php if($block->canPayWithGooglePay()): ?>

    <?php
    $config = [
        'id' => 'google-pay-express-totals',
        'sandbox' => $block->getIsSandbox(),
        'quoteId' => $block->getQuoteId(),
        'googleMerchantName' => $block->getGoogleMerchantName(),
        'googleMerchantId' => $block->getGoogleMerchantId(),
        'globalpayMerchantId' => $block->getMerchantId(),
        'allowedCountries' => $block->getGoogleAllowedShippingCountries(),
        'allowedCards' => $block->getGoogleAllowedCards(),
        'actionSuccess' => $block->getActionSuccess(),
        'grandTotalAmount' => $block->getAmount(),
        'isLoggedIn' => $block->isCustomerLoggedIn(),
        'storeCode' => $block->getStorecode(),
        'currencyCode' => $block->getCurrencyCode(),
    ];
    ?>

    <div id="google-pay-express-totals" data-mage-init='{ "RealexPayments_Googlepay/js/googlepay/express": <?php echo  json_encode($config); ?> }'></div>

<?php endif; ?>