<?php if ($block->escapeHtml($block->getisRealex())) :?>
    <p><?php
        if ($block->getData('is_apm_pending')) {
            echo $block->escapeHtml(__('Your order was received, but the payment is still pending.'));
        } else {
            echo $block->escapeHtml(__('Your payment was successful.'));
        }
        ?></p>
    <?php if ($block->getNewPayer()) :?>
      <p><?php echo $block->escapeHtml(__('Card details successfully and securely stored.'));?></p>
    <?php endif ?>
<?php endif ?>
